### ISSUE TITLE
PYthon 3.5 error: TypeError: __str__ returned non-string (type bytes)

### ISSUE THREAD

**Issue by apiszcz** [scolab-dot-eu/pygdaltools#1]
It may be my argument setup?

```
Traceback (most recent call last):
  File "test2.py", line 43, in <module>
    ogr.execute()
  File "lib\gdaltools\ogr2ogrcmd.py", line 285, in execute
    safe_args.extend([str(self.out_ds), str(self.in_ds), self.in_table])
TypeError: __str__ returned non-string (type bytes)

```

==
```
ogr=gt.ogr2ogr()
con=gt.PgConnectionString(host="localhost",
                                 port=5444,
                                 dbname="tdb",
                                 schema="tests",
                                 user="postgres",
                                 password="")
ogr.set_input(con,
              table_name="2018_testtable",
              srs="EPSG:4326")

ogr.set_output(r'2018_testtable.csv')
```

ogr.execute()

**Comment by dispiste** [comment]
Thanks  for reporting @apiszcz 

I believe it is now fixed in the 1.2 release. Please, report back if it is not working for you.
