### ISSUE TITLE
Error while using ogrinfo with local shp

### ISSUE THREAD

**Issue by HaudelardUpFactor** [scolab-dot-eu/pygdaltools#6]
I've tried to use ogrinfo with a local shp

```python
from gdaltools import ogr2ogr, ogrinfo

info = ogrinfo("test.shp", "thelayer", geom=False)
print(info) # output is the same generated by the ogrinfo command
```

But here is the error I get
```bash
ERROR:root:b''
Traceback (most recent call last):
  File "/upfactor/code/test/exec.py", line 3, in <module>
    info = ogrinfo('test.shp', "thelayer", geom=False)
  File "/home/arthur/.local/lib/python3.9/site-packages/gdaltools/ogrinfocmd.py", line 50, in ogrinfo
    return oinfo.execute()
  File "/home/arthur/.local/lib/python3.9/site-packages/gdaltools/ogrinfocmd.py", line 147, in execute
    return self._do_execute(args)
  File "/home/arthur/.local/lib/python3.9/site-packages/gdaltools/basetypes.py", line 108, in _do_execute
    raise GdalToolsError(rc, err)
gdaltools.basetypes.GdalToolsError: (1, b'')
```

Am I doing something wrong ?

I'm on Ubuntu 20.04

PS : ogr2ogr works perfectly !

```python
ogr = ogr2ogr()
ogr.set_encoding("UTF-8")
ogr.set_input("test.shp", srs="EPSG:4326")
ogr.set_output("test.geojson")
ogr.execute()
```

**Comment by HaudelardUpFactor** [comment]
Ok I understood what was necessary as "the layer".

Everything works perfectly now !
